// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOY3-lbHnAaGexWWmYVVJ_TSy477_KGL8',
    appId: '1:647281240086:web:cf0c1e8c2e101e9d972d37',
    messagingSenderId: '647281240086',
    projectId: 'uni-management-7d0db',
    authDomain: 'uni-management-7d0db.firebaseapp.com',
    storageBucket: 'uni-management-7d0db.firebasestorage.app',
    measurementId: 'G-E6NXR79ET0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClqsV3cOYPyZ4PS3p9okPr4jSpFNSFqCw',
    appId: '1:647281240086:android:4e1c17e3dcea4cde972d37',
    messagingSenderId: '647281240086',
    projectId: 'uni-management-7d0db',
    storageBucket: 'uni-management-7d0db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxKlacRdY8AYKur-QSz10vFNyQCltDAAQ',
    appId: '1:647281240086:ios:c40c2cfd7c394e1a972d37',
    messagingSenderId: '647281240086',
    projectId: 'uni-management-7d0db',
    storageBucket: 'uni-management-7d0db.firebasestorage.app',
    iosBundleId: 'com.example.uniManagementMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxKlacRdY8AYKur-QSz10vFNyQCltDAAQ',
    appId: '1:647281240086:ios:c40c2cfd7c394e1a972d37',
    messagingSenderId: '647281240086',
    projectId: 'uni-management-7d0db',
    storageBucket: 'uni-management-7d0db.firebasestorage.app',
    iosBundleId: 'com.example.uniManagementMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOY3-lbHnAaGexWWmYVVJ_TSy477_KGL8',
    appId: '1:647281240086:web:33ab9f8029dd0fe6972d37',
    messagingSenderId: '647281240086',
    projectId: 'uni-management-7d0db',
    authDomain: 'uni-management-7d0db.firebaseapp.com',
    storageBucket: 'uni-management-7d0db.firebasestorage.app',
    measurementId: 'G-J449RB2HEZ',
  );
}
